### ISSUE TITLE
Error when testing an observable with null emissions

### ISSUE THREAD

**Issue by henry-alakazhang** [kwonoj/rx-sandbox#129]
Hi,

If you try to test an observable that emits `null`, the test fails due to this error inside `constructObservableMarble` when it tries to pick a symbol:

```
TypeError: Cannot read property 'toString' of null
    at appendNotificationValue (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rx-sandbox/dist/src/assert/constructObservableMarble.js:57:1)
    at Object.constructObservableMarble (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rx-sandbox/dist/src/assert/constructObservableMarble.js:103:1)
    at Object.equal (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rx-sandbox/dist/src/assert/marbleAssert.js:41:1)
    at ...
```
Version: 1.0.0

It looks like this is no longer occurs in master thanks to a0956232, so a new release should fix this issue.

**Comment by kwonoj** [comment]
Released 1.0.1, thanks.
